# -*- coding: utf-8 -*-

"""This file was auto-generated by PyFlow exporter
    'Python exporter v1.0.0'
    Created: 07:41AM on September 02, 2025
"""

EXPORTER_NAME = 'Python exporter'
EXPORTER_VERSION = '1.0.0'


# ======================== VARIABLES AND PARAMETERS SETUP =========================
VARS = {}


# ================================ PACKAGE IMPORTS ================================
# pylint: disable=wrong-import-position

# pylint: enable=wrong-import-position

# ================================= PACKAGE SETUPS ================================


# ================================ SYSTEM FUNCTIONS ===============================




# ============================== GRAPH IMPLEMENTATION =============================

def compound(in1):
    makeInt5_out = 2
    multiply_out = (makeInt5_out * in1)
    return multiply_out


# ================================== MAIN PROGRAM =================================


# ------- compound_in -------
makeInt_out = 10
compound_out4 = compound(makeInt_out)
makeString_out = 'done'
print(makeString_out)
