# -*- coding: utf-8 -*-

"""This file was auto-generated by PyFlow exporter
    'Python exporter v1.0.0'
    Created: 12:15AM on September 07, 2025
"""

EXPORTER_NAME = 'Python exporter'
EXPORTER_VERSION = '1.0.0'


# ======================== VARIABLES AND PARAMETERS SETUP =========================
VARS = {}


# ================================ PACKAGE IMPORTS ================================
# pylint: disable=wrong-import-position
import math
# pylint: enable=wrong-import-position

# ================================= PACKAGE SETUPS ================================


# ================================ SYSTEM FUNCTIONS ===============================






# ============================== GRAPH IMPLEMENTATION =============================

def add_one(num):
    makeFloat1_out = 1.0
    add_out = (num + makeFloat1_out)
    return add_out

def square(num):
    makeFloat4_out = 2.0
    power_out, power_result = math.pow(num, makeFloat4_out), True
    return power_out


# ================================== MAIN PROGRAM =================================


# ------- consoleOutput_inExec -------
makeFloat_out = 10.0
Function_new_num = add_one(makeFloat_out)
Function5_new_num = square(Function_new_num)
print(Function5_new_num)
