# -*- coding: utf-8 -*-

"""This file was auto-generated by PyFlow exporter
    'Python exporter v1.0.0'
    Created: 07:42AM on September 02, 2025
"""

EXPORTER_NAME = 'Python exporter'
EXPORTER_VERSION = '1.0.0'


# ======================== VARIABLES AND PARAMETERS SETUP =========================
VARS = {}


# ================================ PACKAGE IMPORTS ================================
# pylint: disable=wrong-import-position

# pylint: enable=wrong-import-position

# ================================= PACKAGE SETUPS ================================


# ================================ SYSTEM FUNCTIONS ===============================


# ============================== GRAPH IMPLEMENTATION =============================


# ================================== MAIN PROGRAM =================================


# ------- branch_In -------
if False:
    print(1.0)
    print(2.0)
    print(3.0)
else:
    print(1.0)
    print(2.0)
