# -*- coding: utf-8 -*-

"""This file was auto-generated by PyFlow exporter
    'Python exporter v1.0.0'
    Created: 10:18PM on August 31, 2025
"""

EXPORTER_NAME = 'Python exporter'
EXPORTER_VERSION = '1.0.0'


# ======================== VARIABLES AND PARAMETERS SETUP =========================
VARS = {}


# ================================ PACKAGE IMPORTS ================================
# pylint: disable=wrong-import-position
import platform
import os
import sys
# pylint: enable=wrong-import-position

# ================================= PACKAGE SETUPS ================================


# ================================ SYSTEM FUNCTIONS ===============================
def clearConsole():  # pylint: disable=invalid-name
    """Clears the console screen in a platform independent way"""
    system = platform.system()
    if system != "":
        system = system.lower()
        if system in ("windows", "win32"):
            os.system("cls")
        if system in ("linux", "darwin", "linux2"):
            os.system("clear")




# ============================== GRAPH IMPLEMENTATION =============================


# ================================== MAIN PROGRAM =================================


# ------- clearConsole_inExec -------
clearConsole()
print('hello from converted world!')
startsWith_out = 'valami'.startswith('va')
print(startsWith_out)
sys.exit(0)
