# -*- coding: utf-8 -*-

"""This file was auto-generated by PyFlow exporter
    'Python exporter v1.0.0'
    Created: 04:50PM on September 06, 2025
"""

EXPORTER_NAME = 'Python exporter'
EXPORTER_VERSION = '1.0.0'


# ======================== VARIABLES AND PARAMETERS SETUP =========================
VARS = {}


# ================================ PACKAGE IMPORTS ================================
# pylint: disable=wrong-import-position

# pylint: enable=wrong-import-position

# ================================= PACKAGE SETUPS ================================


# ================================ SYSTEM FUNCTIONS ===============================


# ============================== GRAPH IMPLEMENTATION =============================


# ================================== MAIN PROGRAM =================================


# ------- consoleOutput_inExec -------
makeInt3_out = 2
makeDictElement1_out = ('two', makeInt3_out)
makeInt4_out = 3
makeDictElement2_out = ('three', makeInt4_out)
makeInt_out = 1
makeDictElement_out = ('one', makeInt_out)
makeDict_out, makeDict_result = dict([makeDictElement1_out,
                                      makeDictElement2_out,
                                      makeDictElement_out]), True
print(makeDict_out)
